### ISSUE TITLE
auth-ldap doesn't populate config during register

### ISSUE THREAD

**Issue by greeble31** [haraka/haraka-plugin-auth-ldap#2]
### system info

Haraka | Haraka.js — Version: 2.8.18
 --- | :---
Node | v7.10.1
OS | Linux ubuntu 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Observed behavior
auth-ldap doesn't work. Broke somewhere b/w .13 and .18, is my guess. Probable root cause: exports.register is missing a line. Should look like this:

`exports.register = function () {
    this.inherits('auth/auth_base');
    this.load_auth_ldap_ini();    //<-- this is the missing line
}
`

Otherwise, the this.cfg is always null:

[CRIT] [C6653449-9CEF-4709-8F29-4E0EA68CBD8B] [core] Plugin auth-ldap failed: TypeError: Cannot read property 'core' of undefined
    at Plugin.exports.check_plain_passwd (/home/greeble31/mail/node_modules/haraka-plugin-auth-ldap/index.js:37:15)
    at Plugin.exports.check_user (/home/greeble31/mail/node_modules/Haraka/plugins/auth/auth_base.js:148:16)
    at Plugin.exports.auth_login (/home/greeble31/mail/node_modules/Haraka/plugins/auth/auth_base.js:233:23)
    at Plugin.exports.hook_unrecognized_command (/home/greeble31/mail/node_modules/Haraka/plugins/auth/auth_base.js:42:23)
.
.
.

Side note: The default config/plugins has bad syntax for the commented auth-ldap: It is "# auth_ldap", but should be "# auth-ldap". Anyone who uncomments that line, expecting it to use the new auth-ldap module, will instead be getting an error message from the old auth_ldap.

### Steps to reproduce

Do a trivial install of Haraka, and enable auth_ldap.

**Comment by r3pek** [comment]
@celesteking The problem is not in the code that's on GitHub, it's in the code that's in NPM. GitHub is right, NPM has an older version.

**Comment by r3pek** [comment]
Actually, the code on github doesn't work either. It still gives the same error. Here's the stack trace:
```
[INFO] [A8102D61-BBAB-491E-9EA2-86962CDBD3A1] [core]  hook=unrecognized_command plugin=auth-ldap function=hook_unrecognized_command params=AUTH retval=OK msg="",
[INFO] [A8102D61-BBAB-491E-9EA2-86962CDBD3A1] [core]  hook=unrecognized_command plugin=auth-ldap function=hook_unrecognized_command params="cjNwZWs=" retval=OK msg="
[CRIT] [A8102D61-BBAB-491E-9EA2-86962CDBD3A1] [core] Plugin auth-ldap failed: TypeError: Cannot read property 'core' of undefined,
    at Plugin.exports.check_plain_passwd (/home/node/.npm-global/lib/node_modules/Haraka/node_modules/haraka-plugin-auth-ldap/index.js:37:16),
    at Plugin.exports.check_user (/home/node/.npm-global/lib/node_modules/Haraka/plugins/auth/auth_base.js:148:16),
    at Plugin.exports.auth_login (/home/node/.npm-global/lib/node_modules/Haraka/plugins/auth/auth_base.js:233:23),
    at Plugin.exports.hook_unrecognized_command (/home/node/.npm-global/lib/node_modules/Haraka/plugins/auth/auth_base.js:42:23),
    at callback (/home/node/.npm-global/lib/node_modules/Haraka/plugins.js:463:32),
    at Plugin.exports.upgrade_connection (/home/node/.npm-global/lib/node_modules/Haraka/plugins/tls.js:93:56),
    at Object.plugins.run_next_hook (/home/node/.npm-global/lib/node_modules/Haraka/plugins.js:505:28),
    at Object.plugins.run_hooks (/home/node/.npm-global/lib/node_modules/Haraka/plugins.js:422:13),
    at Connection.process_line (/home/node/.npm-global/lib/node_modules/Haraka/connection.js:342:25),
[INFO] [A8102D61-BBAB-491E-9EA2-86962CDBD3A1] [max_unrecognized_commands] max: 10, count: 0, fail:Unrecognized command: MTIzNDU=,,
```

**Comment by msimerson** [comment]
Fixed!

````
$ npm publish
+ haraka-plugin-auth-ldap@1.0.1
````
